"""calculations

Revision ID: 0007_calculations
Revises: 0006_price_quotes
Create Date: 2026-09-05 16:44:45.742301
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0007_calculations"
down_revision = "0006_price_quotes"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calculations",
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("coverage_percent", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("position_count", sa.Integer(), nullable=False),
        sa.Column("calculated_count", sa.Integer(), nullable=False),
        sa.Column("cost_total", sa.Float(), nullable=True),
        sa.Column("sale_total", sa.Float(), nullable=True),
        sa.Column("margin_absolute", sa.Float(), nullable=True),
        sa.Column("margin_percent", sa.Float(), nullable=True),
        sa.Column("roi_percent", sa.Float(), nullable=True),
        sa.Column("scenarios", sa.JSON(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("review_notes", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tender_id"),
    )
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calculations_coverage_percent"), ["coverage_percent"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_calculations_margin_percent"), ["margin_percent"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_calculations_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_calculations_verdict"), ["verdict"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calculations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calculations_verdict"))
        batch_op.drop_index(batch_op.f("ix_calculations_score"))
        batch_op.drop_index(batch_op.f("ix_calculations_margin_percent"))
        batch_op.drop_index(batch_op.f("ix_calculations_coverage_percent"))

    op.drop_table("calculations")
    # ### end Alembic commands ###
