"""decisions

Revision ID: 0008_decisions
Revises: 0007_calculations
Create Date: 2026-09-05 18:08:52.788115
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0008_decisions"
down_revision = "0007_calculations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tender_id", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("calculation_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("verdict_at_decision", sa.String(length=32), nullable=True),
        sa.Column("margin_percent_at_decision", sa.Float(), nullable=True),
        sa.Column("sale_total_at_decision", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_decided_at"), ["decided_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_tender_id"), ["tender_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_tender_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_kind"))
        batch_op.drop_index(batch_op.f("ix_decisions_decided_at"))

    op.drop_table("decisions")
    # ### end Alembic commands ###
